version: "3"
# Can also add postgresql service
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A config.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
